[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full" #Full/None
decorations_theme_variant = "Light" # "Dark"
startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 25

[font]
size = 12.0

[cursor.style]
shape = "Block"

[general]

live_config_reload = true

# import = [
#     "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
# ]
