[window]

opacity = 0.95

padding.x = 10
padding.y = 10

decorations = "Full" #Full/None
decorations_theme_variant = "Light" # "Dark"
#startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 25

[font]
size = 12.0

[cursor.style]
shape = "Block"

[general]
import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]
